CREATE DATABASE IF NOT EXISTS cereal_db;
USE cereal_db;

CREATE TABLE IF NOT EXISTS product (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  mfr  VARCHAR(32)  NOT NULL,
  cereal_type VARCHAR(32) NOT NULL,
  calories INT NOT NULL,
  protein  INT NOT NULL,
  fat      INT NOT NULL,
  sodium   INT NOT NULL,
  fiber  FLOAT NOT NULL,
  carbo  FLOAT NOT NULL,
  sugars FLOAT NOT NULL,
  potass FLOAT NOT NULL,
  vitamins INT NOT NULL,
  shelf    INT NOT NULL,
  weight FLOAT NOT NULL,
  cups   FLOAT NOT NULL,
  rating DECIMAL(9,2)  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE IF NOT EXISTS manufacturer (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;